verson: '3'

services:

  vote:
    image: dockersamples/examplevotingapp_vote:before
    ports:
      - 5000:80
    networks:
      - frontend

  redis:
    image: redis:3.2-alpine
    networks:
      - frontend

  worker:
    image: dockersamples/examplevotingapp_worker
    depends_on:
      - "redis"
    networks:
      - frontend
      - backend

  db:
    image: postgres:9.4
    volumes:
      - psqldata:/var/lib/postgresql/data
    networks:
      - backend

  result:
    image: dockersamples/examplevotingapp_result:before
    ports:
      - 50001:80
    networks:
      - backend


networks:
  frontend:
  backend:

volumes:
  psqldata:
